### PR TITLE
Add debug()

### PR DESCRIPTION
**Pull request by retrofox**
Start to use debug() module to follow the watching process.
Just use `DEBUG=watchify` process environment var to activate it.

### CODE REVIEW

**Comment by zertosh** [comment]
@substack I think this is useful, but I've never seen you use `debug` - you should make the final call on this.

**Comment by retrofox** [comment]
I think It's very useful.



For instance right now this screenshot shows that files into node_modules are being watched. does it make sense ?

**Comment by zertosh** [comment]
@retrofox FYI: All files are watched by default. You can ignore them (including node_modules) with the `--ignore-watch` flag or the `ignoreWatch` option.

**Comment by retrofox** [comment]
@zertosh I don't think so

```
  --ignore-watch=GLOB, --iw GLOB    [default: false]

    Ignore monitoring files for changes that match the pattern. Omitting
    the pattern will default to "**/node_modules/**".
```

https://github.com/substack/watchify/blob/master/index.js#L23

**Comment by retrofox** [comment]
Actually the debug line is printing when a new files starts to be watched. It delegates `ignored` to chokidar.

**Comment by retrofox** [comment]
But when I just save any file into `node_modules/` I get the watch event

**Comment by zertosh** [comment]
@retrofox What CLI flag or option did you use exactly?

**Comment by retrofox** [comment]
@zertosh node related with ignoring files

**Comment by retrofox** [comment]
@zertosh We've tried a lot of paths. For instance `./lib/*.js` just to test

**Comment by zertosh** [comment]
your shell might be expanding the glob... try quoting it and/or try `--ignore-watch`. what's the full command you're using?

**Pull request closed without merging**
