### PR TITLE
Manage own ignoring instead of with chokidar

### PR DESCRIPTION
**Pull request by zertosh**
To avoid creating chokidar instances (https://github.com/substack/watchify/pull/202 et al.)

### CODE REVIEW

**Comment by es128** [comment]
Just FYI you could simplify some of your logic here by using [multimatch](https://github.com/sindresorhus/multimatch) or [micromatch](https://github.com/jonschlinkert/micromatch) with their built-in array handling instead of minimatch

**Comment by zertosh** [comment]
thanks @es128 - I'm trying to stick to the matching lib that browserify uses (minimatch via glob), but  I liked what I saw in micromatch.

**Comment by es128** [comment]
multimatch is a pretty thin wrapper around minimatch that will just handle the arrays for you.

**Comment by zertosh** [comment]
superseded by https://github.com/substack/watchify/pull/237 and https://github.com/substack/watchify/commit/7cfb8fa15e38989125f8c67546fe2488ca2f32ce

**Pull request closed without merging**
