### PR TITLE
Add comments about OS X not firing rebuilds.

### PR DESCRIPTION
**Pull request by franleplant**
See [issue](https://github.com/substack/watchify/issues/205)

### CODE REVIEW

**Comment by zertosh** [comment]
Cool. A few things:

* Lines should be under 80 chars - if the link spills over, that part is ok.

* I'd like to use this section to add more things in the future, so how about changing the title to "troubleshooting" instead? Also use lower case for all titles.

* I played with the grammar a bit:

```md
# troubleshooting

## rebuilds on OS X never trigger

It may be related to a bug in `fsevents` (see [#250](https://github.com/substack/watchify/issues/205#issuecomment-98672850)
and [SO](http://stackoverflow.com/questions/26708205/webpack-watch-isnt-compiling-changed-files/28610124#28610124)).
Try the `--poll` flag and/or renaming the project's directory - that might
help.
```

**Comment by franleplant** [comment]
@zertosh there you go my friend. Let me know if you want me to correct something else.

Also, just for curiosity, why the titles in lower case?

**Comment by zertosh** [comment]
Thanks! wrt lowercase, I personally don't care, but that's substack's style so I feel like I should keep it consistent

**Comment by franleplant** [comment]
:+1:

**Pull request merged**
