### PR TITLE
Desktop notifications support

### PR DESCRIPTION
**Pull request by gavocanov**
-n option for Desktop notifications using node-notifier (https://github.com/madhums/node-notifier) for errors and activity

### CODE REVIEW

**Comment by mattdesl** [comment]
Seems like this would make for a good Browserify plugin! Also see errorify:  
https://github.com/zertosh/errorify

**Comment by mattdesl** [comment]
Seems like this would make for a good Browserify plugin! Also see errorify:  
https://github.com/zertosh/errorify

**Comment by zertosh** [comment]
Thanks for the PR @gavocanov but I'm going to have to pass on this.

You can implement this functionality as a plugin for browserify, which then can use with watchify via ` --plugin=MODULE, -p MODULE` flag.

**Comment by gavocanov** [comment]
Ok, thnx for the feedback.

**Pull request closed without merging**
