### PR TITLE
bump browserify to v8

### PR DESCRIPTION
**Pull request by davidpfahler**
Passes all tests. Needed for https://github.com/substack/node-browserify/pull/1043.

### CODE REVIEW

**Comment by davelandry** [comment]
Casting my vote to see this merged.

**Comment by svnlto** [comment]
:+1:

**Comment by wayneashleyberry** [comment]
:+1:

**Comment by lxe** [comment]
:+1:

**Comment by malandrew** [comment]
+1

**Comment by addisonedwardlee** [comment]
This would be awesome!

**Comment by notjrbauer** [comment]
:+1:

**Comment by svnlto** [comment]
@substack can we have this merged?

**Comment by mattliegey** [comment]
:+1:

**Comment by kenzanboo** [comment]
:+1:

**Comment by dcousens** [comment]
ACK, this would resolve https://github.com/substack/watchify/issues/128

**Comment by dcousens** [comment]
Cheers!

**Pull request merged**
