### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by Pleochism**
Fixes bug with JSON requires from JS files not being modularised cleanly.

### CODE REVIEW

**Comment by kumavis** [comment]
I don't know what the side effects are, but this solves the issue I'm running into.

**Comment by Pleochism** [comment]
It definitely breaks grunt-browserify, sadly.

**Comment by kumavis** [comment]
@Pleochism any idea what the underlying issue is? and why this change solves it?

**Comment by Pleochism** [comment]
I don't. I'd guess that it's related to caching of files, but I can't determine what the cache/packageCache properties are used for further up the chain. Unfortunately I won't have time to look at this again for a few days.

**Comment by zertosh** [comment]
@Pleochism @kumavis Can you try `2.5.0`? https://github.com/substack/watchify/pull/160 should have also fixed your issue

**Comment by Pleochism** [comment]
Yep, that did the trick. Works as expected via grunt-browserify as well.

**Pull request closed without merging**
