### PR TITLE
Allow Chokidar options to be passed through

### PR DESCRIPTION
**Pull request by darend**
Issue: #120

### CODE REVIEW

**Comment by markwpearce** [comment]
+1
I like this!

**Comment by callerc1** [comment]
+1 please merge

**Comment by amchang** [comment]
Can we merge this in! Super useful for those Docker Containers...

**Comment by nfvs** [comment]
+1

**Comment by brandonpapworth** [comment]
+1

**Comment by jonbretman** [comment]
:+1:

**Comment by meoguru** [comment]
Any update on this?

**Comment by tomi-roam** [comment]
+1

**Comment by jonbretman** [comment]
@substack - any thoughts on this?

**Comment by zertosh** [comment]
@darend A couple of things: (1) What about command-line args? and docs? (2) You're mutating an `opts` object that doesn't belong to watchify - try something like:

```js
var chokidarOpts = xtend({persistent: true}, opts.chokidar);
```

**Comment by zertosh** [comment]
Sorry for the noise, turns out that this is a pretty common issue with a few nuances - closing and moving discussion to https://github.com/substack/watchify/issues/162

**Pull request closed without merging**
