### PR TITLE
Add some clarification about logging and output.

### PR DESCRIPTION
**Pull request by burdiyan**
It possible that this issue https://github.com/substack/watchify/issues/216#issuecomment-106963850 is not actually the issue, but people misunderstandings. I also had this problem.

### CODE REVIEW

**Comment by zertosh** [comment]
thanks @burdiyan, but aren't the events already clear enough? https://github.com/substack/watchify#wonlog-function-msg-

**Comment by burdiyan** [comment]
Well, they are clear, but at least for me it was not clear that watchify don't log anything on rebuild, which looks like not working thing at the first time :) 

I think more details in the documentation is almost always better than less details :)

Enviado desde mi iPhone

**Comment by zertosh** [comment]
> I think more details in the documentation is almost always better than less details :)

totally agree, but then it should be something smaller that refers to the events - otherwise it's just noise. like "By default, watchify doesn't display any output, see [events](https://github.com/substack/watchify#events) for more info."

**Comment by burdiyan** [comment]
@zertosh I like that :) Changed the commit with this message.

**Comment by zertosh** [comment]
Cool! how about making "events" a link to https://github.com/substack/watchify#events ?

**Comment by zertosh** [comment]
merged as https://github.com/substack/watchify/commit/72447247b0299fafae2f9b5ccd2fcc587ec70cb2

**Comment by zertosh** [comment]
Thanks!

**Pull request closed without merging**
