### PR TITLE
Add version option

### PR DESCRIPTION
**Pull request by caspervonb**

### CODE REVIEW

**Comment by zertosh** [comment]
Nah, `npm ls watchify` already gives you the version.

browserify's CLI already [uses](https://github.com/substack/node-browserify/blob/8ef5af9b45270ff3a438ebd1429f57315570d064/bin/cmd.js#L23-L25) `v` and `version`. So we'd be breaking parity, and we can't use `v` because that's already for verbose.

Frankly the value of this option is not worth the trouble.

**Comment by zertosh** [comment]
Once https://github.com/substack/node-browserify/pull/1222 goes through, we can do this PR without the "V". Also to make it a bit more useful, how about something like?

```js
if (w.argv.version) {
    console.log(
        'watchify v%s (in %s)',
        require('../package.json').version,
        path.dirname(require.resolve('../package.json'))
    )
    console.log(
        'browserify v%s (in %s)',
        require('browserify/package.json').version,
        path.dirname(require.resolve('browserify/package.json'))
    )
    process.exit(0);
}
```

**Comment by caspervonb** [comment]
> Nah, npm ls watchify already gives you the version.

Granted `npm ls watchify` does give you the version **but** that is not necessarily the same as what is in being invoked in the shell through `watchify`, and when asking for the watchify version someone is running they're not likely to check npm.

> Once substack/node-browserify#1222 goes through, we can do this PR without the "V". Also to make it a bit more useful ...

:+1:

**Comment by zertosh** [comment]
I made the changes on your commit https://github.com/substack/watchify/commit/f667e991f95d7d6282a9658c0c4c569e71999003

**Comment by zertosh** [comment]
Thanks! sorry for the long wait on this

**Pull request closed without merging**
